/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.google.gson.Gson;
import controller.ProcessadorCliente;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AulaVO;

/**
 *
 * @author Rafael
 */
public class Aulas extends javax.swing.JFrame {

    /**
     * Creates new form GUIAulas
     */
    ProcessadorCliente processador;
    Gson gson;

    public Aulas(ProcessadorCliente processador) {
        initComponents();
        gson = new Gson();
        this.processador = processador;
        controleCrud(true);
        String mensagem = "7#aula";
        processador.enviarMensagem(mensagem);
        while (!processador.isRecebeuMsg()) {
        /* gambiarra para aguardar o retorno do servidor :D */
        }
        System.out.println("Entrou aqui");
        
        //Preencher combobox
        AulaVO aulavo = new AulaVO();
        aulavo = gson.fromJson(tratarMensagemServidor(processador.getConteudoRecebido()), AulaVO.class);
        jCDisciplinaBusca.removeAllItems();
        jCDisciplina.removeAllItems();
        jCSala.removeAllItems();

        int[] disciplina = new int[10];
        disciplina = aulavo.getDisciplina_associada();
        for (int registro = 0; registro < disciplina.length; registro++){
            jCDisciplinaBusca.addItem(disciplina[registro]);
            jCDisciplina.addItem(disciplina[registro]);
            setLocationRelativeTo(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConteudo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jCDisciplina = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jCSala = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAlunos = new javax.swing.JTable();
        jbSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCDisciplinaBusca = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aulas");

        jLabel2.setText("Conteúdo Programático");

        jTConteudo.setColumns(20);
        jTConteudo.setRows(5);
        jScrollPane1.setViewportView(jTConteudo);

        jLabel3.setText("Disciplina Associada");

        jCDisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Sala de Aula");

        jCSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Alunos Presentes");

        jTAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RA", "Nome", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTAlunos);

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conteúdo", "Professor", "Sala"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jCDisciplinaBusca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Disciplinas");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(166, 166, 166)
                                    .addComponent(jLabel5)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jCDisciplinaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jBPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbSalvar)
                .addGap(29, 29, 29)
                .addComponent(jBEditar)
                .addGap(27, 27, 27)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLimpar)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCDisciplinaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jBEditar)
                    .addComponent(jBExcluir)
                    .addComponent(jBLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String tratarMensagemServidor(String msg) {
        String[] quebra = msg.split(Pattern.quote("#"));
        if (quebra[0].equals("5")) {
            return quebra[1];
        } else {
            return quebra[2];
        }
    }
    
    private void limpaCampo() {
        jTConteudo.setText("");
    }
    
    private void controleCrud(boolean b) {
        jBEditar.setEnabled(!b);
        jBExcluir.setEnabled(!b);
        jbSalvar.setEnabled(b);
    }
    
    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        String mensagem;
        String retornoServidor = "";
        AulaVO aulavo = new AulaVO();
        DefaultTableModel tabela = (DefaultTableModel) jTAlunos.getModel();
        /*String termoBusca = "";
        termoBusca = jCDisciplinaBusca.getSelectedIndex();

        if (!termoBusca.equals("")) {*/
            int disciplina = jCDisciplinaBusca.getSelectedIndex();
            int[] array_disciplina = new int[10];
            array_disciplina[0] = disciplina;
            aulavo.setDisciplina_associada(array_disciplina);
            
            mensagem = "4#"+"aula+"+aulavo;
            processador.enviarMensagem(mensagem);
            while (!processador.isRecebeuMsg()) {
                /* gambiarra para aguardar o retorno do servidor :D */
            }
            aulavo = gson.fromJson(tratarMensagemServidor(processador.getConteudoRecebido()), AulaVO.class);

            if (aulavo != null) {
                jTConteudo.setText(aulavo.getConteudo_programatico());
                
                for(int i = 0; i < jCDisciplina.getItemCount(); i++){
                    /*int[] array_disciplina = new int[10];
                    
                    if(i == aulavo.getDisciplina_associada()){
                        jCDisciplina.setSelectedIndex(aulavo.getDisciplina_associada());
                        break;
                    }*/
                }
                
                for(int i = 0; i < jCSala.getItemCount(); i++){
                    if(i == aulavo.getAula_id()){
                        jCSala.setSelectedIndex(aulavo.getAula_id());
                        break;
                    }
                }
                
                int flagTabela = 0;
                //Verificar como será o retorno dos alunos para o preenchimento da tabela
                /*String aux[] = endCliente.split("#");
                for (int row = 0; row <= tabela.getRowCount() - 1; row++) {
                    if (aux[0].equals(tabela.getValueAt(row, 0)) && aux[1].equals(tabela.getValueAt(row, 1)) && aux[2].equals(tabela.getValueAt(row, 2))) {
                        flagTabela++;
                    }
                }
                    
                if (flagTabela == 0) {
                    tabela.addRow(new String[]{aux[0], aux[1], aux[2]});
                }*/
            }
        //}
        controleCrud(false);
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        String mensagem;
        String retornoServidor = "";
        AulaVO aulavo = new AulaVO();

        aulavo.setConteudo_programatico(jTConteudo.getText());
        //aulavo.setDisciplina_associada(jCDisciplina.getSelectedIndex());
        //aulavo.setSala_aula_associada(jCSala.getSelectedIndex());
        for(int i = 0; i < jTAlunos.getRowCount(); i++){
            if(jTAlunos.getValueAt(i, 2) == true){
                String aluno[] = null;
                aluno[i] = (String) jTAlunos.getValueAt(i, 0);
                aulavo.setAlunos_presentes(aluno);
            }
        }
        
        mensagem = "1#aula"+aulavo;

        processador.enviarMensagem(mensagem);
        while (!processador.isRecebeuMsg()) {
            /* gambiarra para aguardar o retorno do servidor :D */
        }

        retornoServidor = processador.getConteudoRecebido();
        JOptionPane.showMessageDialog(null, tratarMensagemServidor(retornoServidor), "Resposta do Servidor", JOptionPane.INFORMATION_MESSAGE);
        controleCrud(true);
        limpaCampo();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        String mensagem;
        String retornoServidor = "";
        AulaVO aulavo = new AulaVO();

        aulavo.setConteudo_programatico(jTConteudo.getText());
        //aulavo.setDisciplina_associada(jCDisciplina.getSelectedIndex());
        //aulavo.setSala_aula_associada(jCSala.getSelectedIndex());
        for(int i = 0; i < jTAlunos.getRowCount(); i++){
            if(jTAlunos.getValueAt(i, 2) == true){
                String aluno[] = null;
                aluno[i] = (String) jTAlunos.getValueAt(i, 0);
                aulavo.setAlunos_presentes(aluno);
            }
        }
        
        mensagem = "2#aula"+aulavo;

        processador.enviarMensagem(mensagem);
        while (!processador.isRecebeuMsg()) {
            /* gambiarra para aguardar o retorno do servidor :D */
        }

        retornoServidor = processador.getConteudoRecebido();
        JOptionPane.showMessageDialog(null, tratarMensagemServidor(retornoServidor), "Resposta do Servidor", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        String mensagem;
        String retornoServidor = "";
        AulaVO aulavo = new AulaVO();

        aulavo.setConteudo_programatico(jTConteudo.getText());
        //aulavo.setDisciplina_associada(jCDisciplina.getSelectedIndex());
        //aulavo.setSala_aula_associada(jCSala.getSelectedIndex());
        for(int i = 0; i < jTAlunos.getRowCount(); i++){
            if(jTAlunos.getValueAt(i, 2) == true){
                String aluno[] = null;
                aluno[i] = (String) jTAlunos.getValueAt(i, 0);
                aulavo.setAlunos_presentes(aluno);
            }
        }
        
        mensagem = "3#aula"+aulavo;

        processador.enviarMensagem(mensagem);
        while (!processador.isRecebeuMsg()) {
            /* gambiarra para aguardar o retorno do servidor :D */
        }

        retornoServidor = processador.getConteudoRecebido();
        JOptionPane.showMessageDialog(null, tratarMensagemServidor(retornoServidor), "Resposta do Servidor", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpaCampo();
        
    }//GEN-LAST:event_jBLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aulas().setVisible(true);
            }
        });*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JComboBox jCDisciplina;
    private javax.swing.JComboBox jCDisciplinaBusca;
    private javax.swing.JComboBox jCSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTAlunos;
    private javax.swing.JTextArea jTConteudo;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables
}
